### ISSUE TITLE
`charm build` Python exception 

### ISSUE THREAD

**Issue by cmars** [juju/charm-tools#118]
I'm getting a Python exception when trying to run `charm build` on a charm under xenial. I do not get this exception on trusty or wily.

charm-tools installed from ppa:juju/stable

Stack trace: https://paste.ubuntu.com/15260600/

I can work around the issue by removing empty lines from all YAML files that get merged by `charm build`: metadata.yaml, config.yaml, etc.

I can reproduce this issue by introducing empty lines in YAML files that get merged across multiple layers. For example, newlines after each option in a config.yaml.

I think it's possibly related to the different version of python-ruamel.yaml installed on xenial:
```
ii  python-ruamel.yaml                          0.10.23-1                                     amd64        roundtrip YAML parser/emitter (Python 2 module)
```

**Comment by johnsca** [comment]
The problem is actually that [`Path.open()`](https://pythonhosted.org/path.py/api.html#path.Path.open) is returning a [`TextIOWrapper`](https://docs.python.org/2/library/io.html#io.TextIOWrapper) instead of a standard file handle, which is unicode only:

```python
>>> open('/tmp/foo', 'w').write('foo')
>>> open(Path('/tmp/foo'), 'w').write('foo')
>>> Path('/tmp/foo').open('w').write('foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be unicode, not str
```

Should be a simple [one line](https://github.com/juju/charm-tools/blob/master/charmtools/build/tactics.py#L321) fix.
