### ISSUE TITLE
'charm login' requests my password, promises to be good, violates oauth

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#189]
Rather than redirect me to the SSO website where I can enter my password securely, 'charm login' instead requests I enter my password and posts it on my behalf to the SSO website. This requires me to trust charm-tools with my password, and the libraries it uses to correctly verify the chain of trust and refuse to continue if the SSL certificate is not valid (MITM attacks), and does not give me an opportunity to confirm the access level being requested. These are all reasons that the oauth protocol exists in the first place ("OAuth is an authentication protocol that allows users to approve application to act on their behalf without sharing their password.")

What should happen is it opens a browser window to the SSO website where I can login if necessary, do the 2fa dance if necessary, and confirm that I wish to grant the requested access.

**Comment by johnsca** [comment]
Most of the `charm` commands, including login, are actually in https://github.com/juju/charmstore-client and this particular issue is addressed in https://github.com/juju/charmstore-client/issues/44 where the idea of opening a browser window is (unfortunately, IMO) rejected because it sometimes doesn't work.

**Comment by stub42** [comment]
Moved there
