### ISSUE TITLE
charm build in a virtual environment fails

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#25]
I am trying to build a charm with the most current charm-tools code.  My understanding is I can run a virtualenv and pip install the charm-tools source directory.  The "--user" flag for pip makes it impossible to build from a virtualenv.

Here are the steps I performed today.

```
virtualenv /tmp/venv
source /tmp/venv/bin/activate
git clone git@github.com:mbruzek/charm-tools
cd charm-tools
pip install -e .
cd ~/workspace/charms/trusty/layer-docker
(venv)mbruzek@warhorse:~/workspace/charms/trusty/layer-docker$ charm build
build: Composing into /home/mbruzek/workspace/charms
build: Processing layer: layer:basic
build: Processing layer: docker
Traceback (most recent call last):
  File "/tmp/venv/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==1.7.1', 'console_scripts', 'charm-build')()
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/build/__init__.py", line 501, in main
    build()
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/build/__init__.py", line 405, in __call__
    self.generate()
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/build/__init__.py", line 371, in generate
    self.exec_plan(self.plan, self.layers)
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/build/__init__.py", line 349, in exec_plan
    tactic()
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/build/tactics.py", line 435, in __call__
    spec), env=localenv).throw_on_error()()
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/utils.py", line 193, in __call__
    result.throw_on_error()
  File "/home/mbruzek/workspace/git/charm-tools/charmtools/utils.py", line 150, in throw_on_error
    self.exit_code, self.command, output=self.output)
subprocess.CalledProcessError: Command '('pip', 'install', '--user', '--ignore-installed', u'charms.reactive>=0.1.0,
<2.0.0')' returned non-zero exit status 1
```

When I ran the install command manually and found the error:
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
Storing debug log for failure in /home/mbruzek/.pip/pip.log

I tried several things including installing charms.reactive in the virtualenv manually.  The build command always fails because the "--user" option is specified.

**Comment by bcsaller** [comment]
We currently do this as a way of getting a "full" install of the package (so we can pull things like /bin scripts). These are then placed into the charm. We'd need to change the installer (again) to support doing this under a virtualenv and I am not sure we need to support that case. If we can figure out a better way to run the InstallerTactic I am open to it though.

**Comment by mbruzek** [comment]
Cory explained the reason behind the --user flag, and I am OK with changing my workflow.  I created this issue to remind that this is a problem and see if there is a better way to solve this (wheelhouse?) in the future.

**Comment by johnsca** [comment]
The work-around I suggested to @mbruzek was to use a Docker container to test the new charm-tools, rather than a virtualenv.

I asked him to open this issue, though, so that we could discuss alternative ways of handling the `.pypi` dependencies.  Specifically, I was wondering why we didn't go with the approach of building a wheelhouse and then doing an install from that during the deploy?  It would make inspecting the built charm much cleaner without having to add filtering to the inspect library.  Also, a concern with the current approach is that we could still run afoul of issues with non-source-only pypi packages.  With the current scheme, dependencies are potentially being compiled on the build machine which could well be different than the deployed cloud image.  This doesn't come up often, but could be an issue, and I think the wheelhouse approach would resolve it.

**Comment by marcoceppi** [comment]
Another alternative is to use the snap package `snap install charm`
