### ISSUE TITLE
Charm build fails when user id isn't in /etc/passwd

### ISSUE THREAD

**Issue by chris-sanders** [juju/charm-tools#383]
## Checklist

 - [X] Confirmed this is an issue with charm-tools, not charmstore-client
 - [x] Provide versions of tools used
 - [ ] Described the feature or ways to replicate the issue

## What version am I running?

I ran the following command: `snap info charm` and got the following ouput:

```
charm 2.2.2
charm-tools 2.2.3

```

I am using: 
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

## Issue/Feature
Running on a cloud machine which my user is not listed in /etc/passwd produces a Traceback.

### I expect/expected the following

The charm to build.

### What I got

```
Traceback (most recent call last):
  File "/snap/charm/114/bin/charm-build", line 11, in <module>
    load_entry_point('charm-tools==2.2.3', 'console_scripts', 'charm-build')()
  File "/snap/charm/114/lib/python2.7/site-packages/charmtools/build/builder.py", line 746, in main
    build.check_paths()
  File "/snap/charm/114/lib/python2.7/site-packages/charmtools/build/builder.py", line 592, in check_paths
    if path_to_check and not self._check_path(path_to_check):
  File "/snap/charm/114/lib/python2.7/site-packages/charmtools/build/builder.py", line 578, in _check_path
    home_dir = utils.get_home()
  File "/snap/charm/114/lib/python2.7/site-packages/charmtools/utils.py", line 606, in get_home
    username = pwd.getpwuid(os.getuid()).pw_name
KeyError: 'getpwuid(): uid not found: 4639'
```

**Comment by marcoceppi** [comment]
So, I agree this should degrade a lot nicer and I'll put up a patch in a minute. However, could you better explain the circumstances you're running charm-tools with? I don't quite see how you have a user which isn't a well defined user on the system. Understanding this will help us better code defensively to similar situations :sweat_smile:

**Comment by chris-sanders** [comment]
Sure, this is a machine that where user access is being managed by userdir-ldap so that user accounts are managed centrally. This results in no local user account being installed and the home directory being created on first log in. Environment variables like $HOME do work the users simply isn't in the /etc/passwd.

I have confirmed that hacking my userID into /etc/passwd does allow me to build, as does installing a LXD and running the build inside the container although that's not really surprising.

**Comment by marcoceppi** [comment]
Thanks that's good insights. My patch will allow you to continue using your ldap managed userid and not have charm build barf. Once that's merged you can `snap refresh charm --channel edge` until it makes its way through the release pipeline!

**Comment by afreiberger** [comment]
That's quite an interesting work-around.  what will this end up falling back to if it can't determine a homedir based on a password entry?

Since this issue is related to snap-based install of charm-tools, is it possible that the charm-tools needs to pull in something like libnss/libldap/libnis to honor "passwd: compat db" in /etc/nsswitch.conf?


drew@ewah:~$ id drew
uid=4777(drew) gid=2500(warthogs) groups=2500(warthogs),2693(is-sa),2636(procmailers),3145(stg-is-srvmgr),2568(is),2936(bootstack-squad),3142(wendigo-users),110(lxd)
drew@ewah:~$ getent passwd drew
drew:x:4777:2500:Drew Freiberger,,,,:/home/drew:/bin/bash
drew@ewah:~$ more /etc/nsswitch.conf 
# This file is managed by the basenode charm.  Do not make local changes.

passwd:		compat db


The Base OS has the libs to look into the NIS tablespace, but maybe the snap-confinement environment does not.

**Comment by afreiberger** [comment]
That's quite an interesting work-around. what will this end up falling back to if it can't determine a homedir based on a password entry?

Since this issue is related to snap-based install of charm-tools, is it possible that the charm-tools needs to pull in something like libnss/libldap/libnis to honor "passwd: compat db" in /etc/nsswitch.conf?

drew@ewah:$ id drew
uid=4777(drew) [snip]
drew@ewah:$ getent passwd drew
drew:[snip]:/home/drew:/bin/bash
drew@ewah:~$ more /etc/nsswitch.conf

This file is managed by the basenode charm. Do not make local changes.
passwd:	compat db

The Base OS has the libs to look into the NIS tablespace, but maybe the snap-confinement environment does not.

**Comment by marcoceppi** [comment]
The library already accounts for when home_dir is None, this just makes sure the call to determine of a home exists doesn't blow up along the way.

**Comment by afreiberger** [comment]
so, should this then be a bug against snappy-core re: the python pwd library not being able to getpwuid from NIS compat tables?

**Comment by johnsca** [comment]
Marco's PR has been merged, which fixes the stack trace, but this will still lead to a `BuildError`.  I'll submit another PR in a moment that will address the rest of this.

**Comment by johnsca** [comment]
Marco's PR is currently in edge (snap rev 121) and mine will be in shortly.
