### ISSUE TITLE
Add info about layer sha / rev to .build.manifest

### ISSUE THREAD

**Issue by johnsca** [juju/charm-tools#403]
`charm-build` currently creates a `.build.manifest` file with info about what was built.  It would be good to include in that the specific rev or sha for each layer that was built, so that it can be audited exactly what went into building the charm.

**Comment by ajkavanagh** [comment]
I wrote [this](https://gist.github.com/ajkavanagh/ae7b7dc60f0e6e1595e934a48a023548) awhile back, about what sort of things would be good.  I'll also copy this to #404 and #405.  The initial paragraph reads:

# Dependencies in Reactive charms
## Introduction

In the OpenStack team, and potentially elsewhere, there is a need to maintain stable as well as devel charms. With non-reactive charms, this is fairly simple.

However, with reactive charms, when a charm is rebuilt the dependencies are taken from the master branch of the various layers and interfaces, and the charm-helpers library, which is baked into layer-basic, is the latest available on PyPi.

The issue is serious: the OpenStack is unable to support stable/17.02 charms without completely manually rebuilding them based on downloading all of the layers and manually editing wheelhouse.txt files to ensure that the versions that were available at the time the stable was cut are the correct versions, along with any cherry picked patches.

The builds are starting to fail less than six months after the original freeze to stable, which means that patches cannot be cherry-picked back to stable charms.

**Comment by johnsca** [comment]
The main argument against supporting version locking of layers is that it encourages charm authors to lock the versions of their base layers and then forget about them and never update them.  This is especially concerning because, other than informally on the mailing list, there's no notification mechanism for layer updates.

I think this proposal (tracking git sha's or bzr revs in `build-manifest.json` and having the ability to rebuild that) avoids the "set and forget" issue reasonably, since it becomes a build-time locking rather than it being coded into the charm.  This is essentially the "freeze" tool option, but built in to `charm-build`.  Does that seem reasonable?

We would also need to managing locking for the Python dependencies; maybe we can look in to building the wheelhouse using [pipfile](https://github.com/pypa/pipfile) which has built-in support for locking.  I'll open another issue for that.
