### ISSUE TITLE
tempita and yaml dependencies are platform dependent

### ISSUE THREAD

**Issue by stub42** [juju/charm-tools#42]
One of the dependencies pulled in when building a charm with the base layer is tempita, and it builds a platform dependent .so file. This will cause templating to fail on different architectures.

The yaml dependency attempts to link with libyaml. If the necessary dependencies are installed (libyaml-dev), this also builds a platform dependent file.

Some care and feeding will be necessary, perhaps not installing dependencies that can be pulled in as debs.

**Comment by marcoceppi** [comment]
This will be addressed when we move dependencies to wheelhouses instead of
baking them at build time

**Comment by bcsaller** [comment]
Unless we build per arch wheelhouses the problem will be the same. Even
ignoring arch and just talking about versions of libs this could still be
an issue.

**Comment by stub42** [comment]
I think the base layer's hooks will need to install dependencies like pyaml, Tempita, dist_info using apt, in the same manner that charm-helpers already does. In fact, charm-helpers already does so 'pip install charmhelpers --no-deps --no-compile -t lib/' could be all that is needed.

(Or are we unable to assume we have access to a 'main' apt archive for the local i386/arm/whatever architecture? I think it is required for juju to be able to provision the machine in the first place)

**Comment by johnsca** [comment]
Newer versions of pip (newer than is default on trusty) also support `--no-binary :all:` for building the wheelhouse without binary packages and deferring compilation until install.  How do we feel about requiring a newer version of pip for build?

Since the use-case here is for libraries required to bootstrap the charm, we definitely want to include the deps (though source-only versions).

**Comment by marcoceppi** [comment]
What version of pip do we need for this? 1.5.6 is in xenial which we're
targeting for charm-tools upload. If that's the version we need we can
backport to the ppa for trusty we can make that happen. Also, maybe build a
virtualenv for the pip stuff to just bypass archive?

**Comment by stub42** [comment]
For bootstrap, I think we are much better off installing one or two tiny .debs for the platform dependent bootstrap dependencies than a heap of huge ones for all the compilers and libraries and headers required to build these dependencies from source.

**Comment by marcoceppi** [comment]
Not every charm is written for ubuntu. deb isn't a sufficiently enough
cross platform package delivery mechanism whereas python succeeds here

**Comment by stub42** [comment]
On 7 November 2015 at 01:41, Marco Ceppi <notifications@github.com> wrote:

> Not every charm is written for ubuntu. deb isn't a sufficiently enough
> cross platform package delivery mechanism whereas python succeeds here
>

The modules we are talking about cannot be built without installing all the
necessary compilers, headers, libraries etc. These can only be installed in
a platform specific manner (debs for ubuntu). It is much simpler to install
one or two Python modules on the unit in a platform specific manner than it
is to install the entire build chain in a platform specific manner.

-- 
Stuart Bishop <stuart@stuartbishop.net>
http://www.stuartbishop.net/

**Comment by johnsca** [comment]
I believe the libraries in question fall back to pure python implementations if they can't compile.

TBH, a lot of charms are platform specific because they use apt-get.  I don't think there's been a real push for making charms that work on non-Ubuntu systems as well as Ubuntu.  Maybe we can start addressing this with layered charms.

**Comment by marcoceppi** [comment]
Well, there are already charms for windows and centos 6. Having the base layer be locked to one system potentially stifles the community

**Comment by johnsca** [comment]
@marcoceppi I think I was unclear; I agree with you.  I was saying that we should start building the base layer and other tools to start encouraging people to think about their charms on platforms other than Ubuntu.  Make it easy (easier) for a given charm to support those other platforms.  I know that we do have some charms for other platforms, but the vast majority (most of mine included) simply assume Ubuntu, mainly because there was no help for handling those other platforms before.

**Comment by marcoceppi** [comment]
This has been "resolved" by and is something relevant in the layers directly and not in the build process
