### ISSUE TITLE
charm get should prompt when there are more than one series

### ISSUE THREAD

**Issue by mbruzek** [juju/charm-tools#46]
The "charm get" command lead me astray when there were more than one version of a charm in the charm store.  The command:
```
charm get postgresql
``` 
Gave me the precise version when I expected the trusty version.  This caused a problem with a misdirected merge.  

If there are more than one version for a charm can "charm get" prompt the user for which series, or fail gracefully with a message about the series being required for charms that have more than one series?  I am willing to work on this bug myself if no one else wants to do it.

**Comment by mitechie** [comment]
Ideally it'd rely on the charmstore to resolve this with the v4 api so that
it works just like Juju deploy does.

**Comment by mbruzek** [comment]
Rick, thanks for the response. What the behaviour of the v4 api is in the case where there are more than one series for charms?

**Comment by mitechie** [comment]
It picks based on things such as latest lts and some other rules.

**Comment by mitechie** [comment]
So the goal is two fold. One is that the thing you get matches what you get with other tools in Juju. Since things like bundles, charms, etc are setup by the store and there are rules associated with resolving partial names, rather than duplicate that relying on the store make it all consistent. 

You can see this in action with:
https://api.jujucharms.com/charmstore/v4/postgresql/archive
https://api.jujucharms.com/charmstore/v4/precise/postgresql/archive
https://api.jujucharms.com/charmstore/v4/~lazypower/postgresql/archive

**Comment by marcoceppi** [comment]
Get is being deprecated with `charm pull` being the recommended way. For issues regarding that please direct them to charmstore-client repo
