### ISSUE TITLE
only_once help unclear

### ISSUE THREAD

**Issue by jacekn** [juju/charm-tools#94]
I was trying to execute certain function only once in my code.

This does not work:
```
@only_once()
def basenode():
    print("in basenode")
```
```
TypeError: only_once() missing 1 required positional argument: 'action'
```

I tried like this but it also did not work:
```
@only_once("basenode")
def basenode():
    print("in basenode")
```
```
AttributeError: 'str' object has no attribute '__code__'
```
Can documentation be clarified to show correct use of this decorator?

**Comment by johnsca** [comment]
In Python, decorators without arguments don't use empty parentheses.  I.e., it should be used like:

```python
@only_once
def basenode():
    print("in basenode")
```

I agree that the documentation is confusing in that regard and should be clarified.  The decorator could also be changed to also allow empty parens (as well as no parens) but perhaps that would be too "magic" and lead to inconsistent code.

Another consideration that needs to be documented because it is very non-obvious is that, because of an implementation detail, `@only_once` *must* be the innermost decorator, if combined with `@when`, etc.

```python
@when('foo')
@only_once
def basenode():
    print("This will work as expected")

# vs.

@only_once
@when('foo')
def basenode_bad():
    print("This will *not* do what you want!")
```

I think this should probably be fixed, rather than just documented.

**Comment by marcoceppi** [comment]
This issue was moved to juju-solutions/charms.reactive#60
